# Generated by Django 3.2.6 on 2021-08-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='quote',
        ),
        migrations.AddField(
            model_name='comment',
            name='quote',
            field=models.ManyToManyField(blank=True, db_column='quote_id', related_name='quote_comments', to='forum.Comment', verbose_name='Ссылки на цитаты комментарев'),
        ),
    ]
