# Generated by Django 3.2.6 on 2021-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210808_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(db_index=True, help_text='Комментарий превышает 3000 символов', max_length=5000, verbose_name='Комментарий пользователя'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='Текст к теме'),
        ),
    ]
