# Generated by Django 3.2.6 on 2021-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210808_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Ссылка на тему'),
        ),
    ]
