# Generated by Django 3.2.6 on 2021-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_theme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Комментарий превышает 5000 символов', max_length=5000, verbose_name='Комментарий пользователя'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content',
            field=models.TextField(help_text='Комментарий превышает 5000 символов', max_length=5000, verbose_name='Текст к теме'),
        ),
    ]
